Finalproject/Models/Specials.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Finalproject.Models
{
    public class Specials
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(250)]
        public string Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
        [MaxLength(50)]
        public string Model { get; set; }
        [MaxLength(50)]
        public string Brand { get; set; }
        [MaxLength(50)]
        public string Color { get; set; }
        [MaxLength(100)]
        public string Price { get; set; }
        [MaxLength(100)]
        public string Discount { get; set; }
        [MaxLength(100)]
        public string Discountfaiz { get; set; }
    }
}

Finalproject/Areas/admin/Controllers/SpecialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Finalproject.Data;
using Finalproject.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace Finalproject.Areas.admin.Controllers
{
    [Area("admin")]
    public class SpecialsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SpecialsController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: admin/Specials
        public async Task<IActionResult> Index()
        {
            return View(await _context.Specials.ToListAsync());
        }

        // GET: admin/Specials/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specials = await _context.Specials
                .FirstOrDefaultAsync(m => m.Id == id);
            if (specials == null)
            {
                return NotFound();
            }

            return View(specials);
        }

        // GET: admin/Specials/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: admin/Specials/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Specials specials)
        {

            if (ModelState.IsValid)
            {
                if (specials.ImageFile != null)
                {
                    if (specials.ImageFile.ContentType == "image/jpeg" || specials.ImageFile.ContentType == "image/png")
                    {
                        if (specials.ImageFile.Length <= 3000000)
                        {
                            string FileName = Guid.NewGuid() + "-" + specials.ImageFile.FileName;
                            string FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploadsspecials", FileName);
                            using (var stream = new FileStream(FilePath, FileMode.Create))
                            {
                                specials.ImageFile.CopyTo(stream);
                            }
                            specials.Image = FileName;
                            _context.Specials.Add(specials);
                            await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(Index));

                        }
                        else
                        {
                            ModelState.AddModelError("", "you can choose only 3 mb image file");
                            return View(specials);
                        }


                    }
                    else
                    {
                        ModelState.AddModelError("", "you can choose only image file");
                        return View(specials);

                    }

                }
                else
                {
                    ModelState.AddModelError("", " choose image file");
                    return View(specials);

                }


            }
            return View(specials);
        }

        // GET: admin/Specials/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specials = await _context.Specials.FindAsync(id);
            if (specials == null)
            {
                return NotFound();
            }
            return View(specials);
        }

        // POST: admin/Specials/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Specials specials)
        {
            if (ModelState.IsValid)
            {
                if (specials.ImageFile != null)
                {
                    if (specials.ImageFile.ContentType == "image/jpeg" || specials.ImageFile.ContentType == "image/png")
                    {
                        if (specials.ImageFile.Length <= 3000000)
                        {
                            string olddata = Path.Combine(_webHostEnvironment.WebRootPath, "Uploadsspecials", specials.Image);
                            if (System.IO.File.Exists(olddata))
                            {
                                System.IO.File.Delete(olddata);
                            }
                            string FileName = Guid.NewGuid() + "-" + specials.ImageFile.FileName;
                            string FilePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploadsspecials", FileName);
                            using (var stream = new FileStream(FilePath, FileMode.Create))
                            {
                                specials.ImageFile.CopyTo(stream);
                            }
                            specials.Image = FileName;
                            _context.Specials.Update(specials);
                            await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(Index));

                        }
                        else
                        {
                            ModelState.AddModelError("", "you can choose only 3 mb image file");
                            return View(specials);
                        }


                    }
                    else
                    {
                        ModelState.AddModelError("", "you can choose only image file");
                        return View(specials);

                    }

                }
                else
                {
                    ModelState.AddModelError("", " choose image file");
                    return View(specials);

                }

            }

            return View(specials);
        }

        // GET: admin/Specials/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specials = await _context.Specials
                .FirstOrDefaultAsync(m => m.Id == id);
            if (specials == null)
            {
                return NotFound();
            }

            return View(specials);
        }

        // POST: admin/Specials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var specials = await _context.Specials.FindAsync(id);
            string olddata = Path.Combine(_webHostEnvironment.WebRootPath, "Uploadsspecials", specials.Image);
            if (System.IO.File.Exists(olddata))
            {
                System.IO.File.Delete(olddata);
            }
            _context.Specials.Remove(specials);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpecialsExists(int id)
        {
            return _context.Specials.Any(e => e.Id == id);
        }
    }
}

Finalproject/Controllers/SpecialsController.cs
using Finalproject.Data;
using Finalproject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Finalproject.Controllers
{
    public class SpecialsController : Controller
    {

        private readonly AppDbContext _context;
        public SpecialsController(AppDbContext context)
        {
            _context = context;

        }
        public IActionResult Index()
        {
            VmHome model = new VmHome()
            {
                Specials = _context.Specials.ToList(),
            };

            return View(model);
        }
        public IActionResult SpecialDeatails(int? id)
        {
            return View(_context.Specials.Find(id));
        }
    }
}

Finalproject/Views/Specials/Index.cshtml
@model VmHome
@{
    ViewData["Title"] = "Index";
}

<section id="titleforall">
    <div class="titlecontact">
        <i class="fa-solid fa-house"></i>
        <p>Specials</p>
    </div>

</section>


<section id="left">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="forborder">
                    <h5>Information</h5>
                    <a href="">
                        <p>About us</p>
                    </a>
                    <a href="">
                        <p>Delivery Information </p>
                    </a>
                    <a href="">
                        <p>Privacy Policy </p>
                    </a>
                    <a href="">
                        <p>Terms & Conditions </p>
                    </a>
                    <a href="">
                        <p>Contact Us </p>
                    </a>
                </div>

                <img class="reklamucun" src="/img/left-banner-315x460 (1).jpg" alt="">
                <div class="forborder">
                    <h5>Latest</h5>

                    <div class="d-flex forhoverimage">
                        <a href="">
                            <div class="imgg">

                            </div>
                            <div class="latest">
                                MacBook Pro (Retina, 15-inch, 8-Core CPU)
                                <div class="d-flex">
                                    <p class="latestp1">$26.00</p>
                                    <p class="latestp2">$241.99</p>
                                </div>
                            </div>

                        </a>

                    </div>
                    <div class="d-flex forhoverimage">
                        <a href="">
                            <div class="imgg">

                            </div>
                            <div class="latest">
                                MacBook Pro (Retina, 15-inch, 8-Core CPU)
                                <div class="d-flex">
                                    <p class="latestp1">$26.00</p>
                                    <p class="latestp2">$241.99</p>
                                </div>
                            </div>

                        </a>

                    </div>
                    <div class="d-flex forhoverimage">
                        <a href="">

                            <div class="imgg">

                            </div>
                            <div class="latest">
                                MacBook Pro (Retina, 15-inch, 8-Core CPU)
                                <div class="d-flex">
                                    <p class="latestp1">$26.00</p>
                                    <p class="latestp2">$241.99</p>
                                </div>
                            </div>

                        </a>

                    </div>


                </div>

            </div>
            <div class="col-lg-8">
                <div class="row">
                    <div class="container">
                        <div class="row">
                            @foreach (var item in Model.Specials)
                            {
                                <div class="col-lg-4   col-md-4 col-6  specialsimage">
                                    <div class="card">
                                        <img src="~/Uploadsspecials/@item.Image" alt="">
                                        
                                        <span class="specialspan">@item.Discountfaiz</span>
                                        <div class="card-body">
                                            <a asp-controller="Specials" asp-action="SpecialDeatails" asp-route-id="@item.Id"> <h6 class="card-title">@item.Brand (@item.Color) </h6></a>
                                            <div class="d-flex">
                                                <h5 class="latestp1">@item.Discount</h5>
                                                <p class="latestp2">@item.Price</p>
                                            </div>
                                            <i class="fa-solid fa-cart-shopping c1"></i>
                                            <a href="#" class="btn btn-primary foradd">Add to Cart</a>
                                        </div>
                                    </div>
                                </div>

                            }

                        </div>
                    </div>

                </div>
            </div>



        </div>


    </div>
</section>


<section id="button">
    <a class="top_button" title="Back To Top" href="#" style="display: block;"></a>
</section>

Finalproject/Views/Specials/SpecialDeatails.cshtml
@model Specials
@{
    ViewData["Title"] = "SpecialDeatails";
}

<section id="left">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="forborder">
                    <h5>Information</h5>
                    <a href="">
                        <p>About us</p>
                    </a>
                    <a href="">
                        <p>Delivery Information </p>
                    </a>
                    <a href="">
                        <p>Privacy Policy </p>
                    </a>
                    <a href="">
                        <p>Terms & Conditions </p>
                    </a>
                    <a href="">
                        <p>Contact Us </p>
                    </a>
                </div>

                <img class="reklamucun" src="/img/left-banner-315x460 (1).jpg" alt="">
                <div class="forborder">
                    <h5>Latest</h5>

                    <div class="d-flex forhoverimage">
                        <a href="">
                            <div class="imgg">

                            </div>
                            <div class="latest">
                                MacBook Pro (Retina, 15-inch, 8-Core CPU)
                                <div class="d-flex">
                                    <p class="latestp1">$26.00</p>
                                    <p class="latestp2">$241.99</p>
                                </div>
                            </div>

                        </a>

                    </div>
                    <div class="d-flex forhoverimage">
                        <a href="">
                            <div class="imgg">

                            </div>
                            <div class="latest">
                                MacBook Pro (Retina, 15-inch, 8-Core CPU)
                                <div class="d-flex">
                                    <p class="latestp1">$26.00</p>
                                    <p class="latestp2">$241.99</p>
                                </div>
                            </div>

                        </a>

                    </div>
                    <div class="d-flex forhoverimage">
                        <a href="">

                            <div class="imgg">

                            </div>
                            <div class="latest">
                                MacBook Pro (Retina, 15-inch, 8-Core CPU)
                                <div class="d-flex">
                                    <p class="latestp1">$26.00</p>
                                    <p class="latestp2">$241.99</p>
                                </div>
                            </div>

                        </a>

                    </div>


                </div>

            </div>
            <div class="col-lg-8">
                <div class="row">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12  specialsimage">
                                <div class="card">
                                    <img class="tukendim" src="~/Uploadsspecials/@Model.Image" alt="">
                                    <span class="specialspan">@Model.Discountfaiz</span>
                                    <div class="card-body">
                                        <h6 class="card-title">@Model.Brand</h6>
                                        <div>
                                            <p>Brand:@Model.Model</p>
                                            <p>Model:@Model.Brand</p>
                                            <p>Color:@Model.Color</p>
                                        </div>
                                       

                                        <div class="d-flex">
                                            <h5 class="latestp1">$26.00</h5>
                                            <p class="latestp2">$241.99</p>
                                        </div>
                                        <i class="fa-solid fa-cart-shopping c1"></i>
                                        <a href="#" class="btn btn-primary foradd">Add to Cart</a>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                    </div>

                </div>
            </div>



        </div>


    </div>
</section>